# Generated by Django 4.1.7 on 2023-02-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('vacancy_name', models.CharField(max_length=255, verbose_name='Vacancy name')),
                ('vacancy_link', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Vacancy link')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company name')),
                ('company_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company link')),
                ('responded', models.BooleanField(default=False, verbose_name='Responded to a vacancy')),
            ],
            options={
                'verbose_name': 'Job vacancy',
                'verbose_name_plural': 'Job vacancies',
            },
        ),
    ]
