# Generated by Django 4.1.7 on 2023-03-02 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_hh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation'),
        ),
    ]
